<?php

namespace ContainerHPjOxnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllercreateOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.axWvN5H.App\Controller\API\OrderController::createOrder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.axWvN5H.App\\Controller\\API\\OrderController::createOrder()'] = ($container->privates['.service_locator.axWvN5H'] ?? $container->load('get_ServiceLocator_AxWvN5HService'))->withContext('App\\Controller\\API\\OrderController::createOrder()', $container);
    }
}
