<?php

namespace ContainerHPjOxnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\API\OrderController' shared autowired service.
     *
     * @return \App\Controller\API\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/API/OrderController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CheckoutService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BaseService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/OrderService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        $container->services['App\\Controller\\API\\OrderController'] = $instance = new \App\Controller\API\OrderController(new \App\Service\CheckoutService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), $a), $a, new \App\Service\OrderService($a, ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\API\\OrderController', $container));

        return $instance;
    }
}
