<?php

namespace ContainerHPjOxnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProductService' shared autowired service.
     *
     * @return \App\Service\ProductService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ProductService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ProductService'])) {
            return $container->privates['App\\Service\\ProductService'];
        }

        return $container->privates['App\\Service\\ProductService'] = new \App\Service\ProductService($a);
    }
}
