<?php

namespace ContainerHPjOxnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerlistProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P7gSmYq.App\Controller\API\ProductController::listProducts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P7gSmYq.App\\Controller\\API\\ProductController::listProducts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productService' => ['privates', 'App\\Service\\ProductService', 'getProductServiceService', true],
        ], [
            'productService' => 'App\\Service\\ProductService',
        ]))->withContext('App\\Controller\\API\\ProductController::listProducts()', $container);
    }
}
