<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'sku' => [parent::class, 'sku', null],
        "\0".parent::class."\0".'specialPrice' => [parent::class, 'specialPrice', null],
        "\0".parent::class."\0".'specialQuantity' => [parent::class, 'specialQuantity', null],
        "\0".parent::class."\0".'unitPrice' => [parent::class, 'unitPrice', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'sku' => [parent::class, 'sku', null],
        'specialPrice' => [parent::class, 'specialPrice', null],
        'specialQuantity' => [parent::class, 'specialQuantity', null],
        'unitPrice' => [parent::class, 'unitPrice', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
