<?php

namespace Container8sxentx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SVfEC_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SVfEC.p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SVfEC.p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\API\\OrderController::createOrder' => ['privates', '.service_locator.axWvN5H.App\\Controller\\API\\OrderController::createOrder()', 'getOrderControllercreateOrderService', true],
            'App\\Controller\\API\\OrderController::getOrders' => ['privates', '.service_locator.aV.y5Ii.App\\Controller\\API\\OrderController::getOrders()', 'getOrderControllergetOrdersService', true],
            'App\\Controller\\API\\OrderController::updateOrderStatus' => ['privates', '.service_locator.axWvN5H.App\\Controller\\API\\OrderController::updateOrderStatus()', 'getOrderControllerupdateOrderStatusService', true],
            'App\\Controller\\API\\ProductController::listProducts' => ['privates', '.service_locator.P7gSmYq.App\\Controller\\API\\ProductController::listProducts()', 'getProductControllerlistProductsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\API\\OrderController:createOrder' => ['privates', '.service_locator.axWvN5H.App\\Controller\\API\\OrderController::createOrder()', 'getOrderControllercreateOrderService', true],
            'App\\Controller\\API\\OrderController:getOrders' => ['privates', '.service_locator.aV.y5Ii.App\\Controller\\API\\OrderController::getOrders()', 'getOrderControllergetOrdersService', true],
            'App\\Controller\\API\\OrderController:updateOrderStatus' => ['privates', '.service_locator.axWvN5H.App\\Controller\\API\\OrderController::updateOrderStatus()', 'getOrderControllerupdateOrderStatusService', true],
            'App\\Controller\\API\\ProductController:listProducts' => ['privates', '.service_locator.P7gSmYq.App\\Controller\\API\\ProductController::listProducts()', 'getProductControllerlistProductsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\API\\OrderController::createOrder' => '?',
            'App\\Controller\\API\\OrderController::getOrders' => '?',
            'App\\Controller\\API\\OrderController::updateOrderStatus' => '?',
            'App\\Controller\\API\\ProductController::listProducts' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\API\\OrderController:createOrder' => '?',
            'App\\Controller\\API\\OrderController:getOrders' => '?',
            'App\\Controller\\API\\OrderController:updateOrderStatus' => '?',
            'App\\Controller\\API\\ProductController:listProducts' => '?',
        ]);
    }
}
