<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8sxentx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8sxentx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8sxentx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8sxentx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8sxentx\App_KernelDevDebugContainer([
    'container.build_hash' => '8sxentx',
    'container.build_id' => '7a9f502a',
    'container.build_time' => 1740835626,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8sxentx');
