<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt_stylesheet' => [[], ['_controller' => 'web_profiler.controller.profiler::toolbarStylesheetAction'], [], [['text', '/_wdt/styles']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_order_create' => [[], ['_controller' => 'App\\Controller\\API\\OrderController::createOrder'], [], [['text', '/api/v1/orders/create']], [], [], []],
    'api_order_get' => [['id'], ['_controller' => 'App\\Controller\\API\\OrderController::getOrder'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/orders']], [], [], []],
    'api_order_list' => [[], ['_controller' => 'App\\Controller\\API\\OrderController::getOrders'], [], [['text', '/api/v1/orders']], [], [], []],
    'api_order_items_list' => [['id'], ['_controller' => 'App\\Controller\\API\\OrderController::getItems'], [], [['text', '/items'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/orders']], [], [], []],
    'api_order_update_status' => [['id'], ['_controller' => 'App\\Controller\\API\\OrderController::updateOrderStatus'], [], [['text', '/update-status'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/orders']], [], [], []],
    'api_order_delete' => [['id'], ['_controller' => 'App\\Controller\\API\\OrderController::deleteOrder'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/orders']], [], [], []],
    'api_product_list' => [[], ['_controller' => 'App\\Controller\\API\\ProductController::listProducts'], [], [['text', '/api/v1/products']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'products' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/products']], [], [], []],
];
